<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Cyotek.Windows.Forms.ColorPicker" Version="1.7.2" />
    <PackageVersion Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>