<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<OutputType>WinExe</OutputType>
		<NoWarn>$(NoWarn);CA1416</NoWarn>
		<RootNamespace>DnG_AdK_Mapedit</RootNamespace>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon>Egyptian builder.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Environment presets\Alpine Valley.bin" />
	  <None Remove="Environment presets\Autumn.bin" />
	  <None Remove="Environment presets\Blizzard.bin" />
	  <None Remove="Environment presets\Blood Moon.bin" />
	  <None Remove="Environment presets\Canyon.bin" />
	  <None Remove="Environment presets\Desert.bin" />
	  <None Remove="Environment presets\Full Moon.bin" />
	  <None Remove="Environment presets\German Coast.bin" />
	  <None Remove="Environment presets\Haunted Marsh.bin" />
	  <None Remove="Environment presets\Iceberg.bin" />
	  <None Remove="Environment presets\Lava Land.bin" />
	  <None Remove="Environment presets\Meadows.bin" />
	  <None Remove="Environment presets\Mediterranean.bin" />
	  <None Remove="Environment presets\Rainforest.bin" />
	  <None Remove="Environment presets\Sand Storm.bin" />
	  <None Remove="Environment presets\Savanna.bin" />
	  <None Remove="Environment presets\Scotland.bin" />
	  <None Remove="Environment presets\South China.bin" />
	  <None Remove="Environment presets\Swamp.bin" />
	  <None Remove="Environment presets\The Alps.bin" />
	  <None Remove="Environment presets\Thunderstorm.bin" />
	  <None Remove="Environment presets\Tundra.bin" />
	  <None Remove="Environment presets\Violet Haze.bin" />
	  <None Remove="Environment presets\Volcanic Dust.bin" />
	  <None Remove="Environment presets\Warm Archipelago.bin" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Environment presets\Alpine Valley.bin" />
		<EmbeddedResource Include="Environment presets\Blizzard.bin" />
		<EmbeddedResource Include="Environment presets\Blood Moon.bin" />
		<EmbeddedResource Include="Environment presets\Canyon.bin" />
		<EmbeddedResource Include="Environment presets\Desert.bin" />
		<EmbeddedResource Include="Environment presets\Full Moon.bin" />
		<EmbeddedResource Include="Environment presets\German Coast.bin" />
		<EmbeddedResource Include="Environment presets\Haunted Marsh.bin" />
		<EmbeddedResource Include="Environment presets\Iceberg.bin" />
		<EmbeddedResource Include="Environment presets\Lava Land.bin" />
		<EmbeddedResource Include="Environment presets\Meadows.bin" />
		<EmbeddedResource Include="Environment presets\Mediterranean.bin" />
		<EmbeddedResource Include="Environment presets\Rainforest.bin" />
		<EmbeddedResource Include="Environment presets\Sand Storm.bin" />
		<EmbeddedResource Include="Environment presets\Savanna.bin" />
		<EmbeddedResource Include="Environment presets\Scotland.bin" />
		<EmbeddedResource Include="Environment presets\South China.bin" />
		<EmbeddedResource Include="Environment presets\Swamp.bin" />
		<EmbeddedResource Include="Environment presets\The Alps.bin" />
		<EmbeddedResource Include="Environment presets\Thunderstorm.bin" />
		<EmbeddedResource Include="Environment presets\Tundra.bin" />
		<EmbeddedResource Include="Environment presets\Violet Haze.bin" />
		<EmbeddedResource Include="Environment presets\Volcanic Dust.bin" />
		<EmbeddedResource Include="Environment presets\Warm Archipelago.bin" />
		<EmbeddedResource Include="MP_6P_snowflake.s2m" />
		<EmbeddedResource Include="Included sacrifice presets\Empty.dams" />
		<EmbeddedResource Include="Included sacrifice presets\Naval battle.dams" />
		<EmbeddedResource Include="Included sacrifice presets\Standard %28enemies close%29.dams" />
		<EmbeddedResource Include="Included sacrifice presets\Standard.dams" />
		<EmbeddedResource Include="Included sacrifice presets\Corridors.dams" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="decryptor_s2.exe" />
		<Content Include="Egyptian builder.ico" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Environment presets\Autumn.bin" />
	</ItemGroup>
</Project>